plugins:
  - ./bundles/@yarnpkg/plugin-script-tools.js
  - path: .yarn/plugins/@yarnpkg/plugin-check.cjs
    spec: "https://raw.githubusercontent.com/zemd/yarn-plugin-check/main/bundles/%40yarnpkg/plugin-check.js"

yarnPath: .yarn/releases/yarn-berry.cjs
